spring.application.name=transactionService
server.port=8090
management.endpoints.web.exposure.include=prometheus,metrics,health
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

#redis 
#spring.redis.cluster.nodes=127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005
spring.webflux.cors.allowed-origins=http://localhost:3001
spring.webflux.cors.allow-credentials=true
spring.main.allow-bean-definition-overriding=true
# Tomcat-specific settings
server.tomcat.max-threads=200
server.tomcat.max-connections=500
server.tomcat.accept-count=500
spring.rest.client.connection-timeout=30000
spring.rest.client.read-timeout=60000
http.client.connect-timeout=10000
http.client.request-timeout=10000
http.client.socket-timeout=30000
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.leak-detection-threshold=60000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.validation-timeout=5000

logging.level.com.zaxxer.hikari=DEBUG
#PostgreSql
spring.datasource.url=jdbc:postgresql://localhost:5432/microservices
spring.datasource.username=kong
spring.datasource.password=postgres
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.error.include-message=always
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
#Kafka Broker
spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.bootstrap-servers=localhost:9093
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=com.javaservice.Service.Config.TransactionSerializer
spring.kafka.producer.partitioner=org.apache.kafka.clients.producer.internals.DefaultPartitioner
spring.kafka.producer.acks=1
spring.kafka.producer.linger-ms=0
spring.kafka.producer.retries=3
spring.kafka.producer.buffer.memory=33554432
spring.kafka.producer.batch.size=1024
spring.kafka.producer.compression-type=none
spring.kafka.producer.properties.enable.idempotence=false
spring.kafka.producer.properties.enable.telemetry=false
spring.kafka.producer.properties.socket.timeout.ms=60000
spring.kafka.producer.properties.max.block.ms=60000
spring.kafka.producer.max.in.flight.requests.per.connection=5
spring.kafka.producer.retry-backoff.ms=1000
spring.kafka.producer.request-timeout=300000
spring.kafka.producer.delivery-timeout=120000
spring.kafka.producer.topic.metadata.refresh.interval.ms=20
spring.kafka.producer.properties.enable.auto.offset.store=true
spring.kafka.producer.properties.enable.auto.commit=true

spring.task.execution.pool.enabled=false
# application.properties
logging.level.org.springframework.scheduling=DEBUG

logging.level.=TRACE
log4j.logger.kafka=DEBUG
logging.level.org.springframework.web=DEBUG




#spring.kafka.producer.min.insync.replicas=2
#org.springframework.kafka.support.serializer.JsonSerializer
#com.javaservice.Service.Kafka.TransactionSerializer
#spring.kafka.producer.transaction-id-prefix=txn-
#spring.kafka.producer.transactional-id=txn-123
#spring.kafka.producer.transaction-timeout=900000
#spring.kafka.producer.request-timeout=120000
